version: '3.8'

x-app: &app
  build:
    context: .dockerdev
    dockerfile: Dockerfile.development
    args:
      RUBY_VERSION: '2.7.3'
      PG_MAJOR: '13'
      NODE_MAJOR: '12'
      YARN_VERSION: '1.22.5'
      BUNDLER_VERSION: '2.1.4'
  environment: &env
    NODE_ENV: ${NODE_ENV:-development}
    RAILS_ENV: ${RAILS_ENV:-development}
  image: gcr.io/opencspm/engine:local-dev
  tmpfs:
    - /tmp

x-backend: &backend
  <<: *app
  stdin_open: true
  tty: true
  volumes:
    - .:/app:cached
    - ../assets:/app/data
    - ../config:/app/load_config
    - ../../opencspm-controls:/app/controls/:ro
    - .dockerdev/.psqlrc:/app/.psqlrc:ro
    - .dockerdev/.bashrc:/app/.bashrc:ro
    - gems:/gems
    - rails_cache:/app/tmp/cache
    - node_modules:/app/ui/node_modules
    - ~/.config/gcloud/opencspm-loader.json:/tmp/keys/credentials.json:ro
  environment:
    <<: *env
    REDIS_URL: redis://redis:6379/
    DATABASE_URL: postgres://postgres:postgres@db:5432
    BOOTSNAP_CACHE_DIR: /gems/_bootsnap
    WEB_CONCURRENCY: ${WEB_CONCURRENCY:-1}
    HISTFILE: /app/log/.bash_history
    PSQL_HISTFILE: /app/log/.psql_history
    EDITOR: vi
    MALLOC_ARENA_MAX: 2
    GOOGLE_APPLICATION_CREDENTIALS: /tmp/keys/credentials.json
    DEBUGGER: 'false'
  depends_on:
    - db
    - redis

services:
  core:
    <<: *backend
    hostname: core
    command: ./init.sh
    restart: unless-stopped
    ports:
      - '4444:4444'
      - '5000:5000'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:5000/healthz']
      interval: 5s
      timeout: 5s
      retries: 11
  ui:
    <<: *backend
    hostname: ui
    working_dir: /app/ui
    command: ./init.sh
    ports:
      - '8000:8080'
    depends_on:
      - core

  worker:
    <<: *backend
    hostname: worker
    command: bundle exec sidekiq -C config/sidekiq.yml
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'pgrep', '-x', 'bundle']
      interval: 10s
      retries: 3
    depends_on:
      - core
      - db
      - redis

  db:
    image: gcr.io/opencspm/postgres:13.2
    hostname: db
    volumes:
      - .dockerdev/.psqlrc:/root/.psqlrc:ro
      - postgres:/var/lib/postgresql/data
      - ./log:/root/log:cached
    environment:
      PSQL_HISTFILE: /root/log/.psql_history
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s

  redis:
    image: gcr.io/opencspm/redisgraph:edge-0.0.1
    hostname: redis
    volumes:
      - redis:/data
    ports:
      - '6379:6379'
    restart: unless-stopped
    healthcheck:
      test: redis-cli ping
      interval: 2s
      timeout: 3s
      retries: 30

  redis_ui:
    image: docker.io/redislabs/redisinsight:latest
    hostname: redis_ui
    ports:
      - '8001:8001'
    restart: unless-stopped
    depends_on:
      - redis

  shell:
    <<: *backend
    command: /bin/bash
    hostname: shell

volumes:
  gems:
  postgres:
  redis:
  node_modules:
  rails_cache:
